### ISSUE TITLE
Add missing locks.

### ISSUE THREAD

**Issue by NullHypothesis** [brave-experiments/star-randsrv#35]
At the very least, we want a read lock [here](https://github.com/brave-experiments/star-randsrv/blob/27c5fcd6663ac694ebc531c0d0816905e5ee8d1b/main.go#L116), and possibly in other places too.

**Comment by NullHypothesis** [comment]
And also consider passing `srv.epochLen` into the function as a variable and remove it from the server object.

**Comment by rillian** [comment]
> And also consider passing `srv.epochLen` into the function as a variable and remove it from the server object.

Unfortunately I don't think this will work; `srv.getEpoch()` called by the both the `/info` and `/randomness` handlers, and it uses `srv.epochLen` for its internal calculations.

I think the answer to why we don't have locking in `epochLoop` is that it's not really necessary. The `srv.puncture` and `srv.init` methods both lock internally. Locking a level up in `epochLoop` to make sure the puncture+init sequence happens atomically means clients block while the OPRF key is rotated instead of getting an error, which is nice, but it makes the calls more error-prone since we can't use `Lock` and `defer srv.Unlock` inside the methods.

Other accesses are to `epochLen` and `firstEpochTime` (through `getEpoch()`) which the code treats as read-only. These are set by `NewServer()` and both `getEpoch` and `epochLoop` use dead reckoning to compute the epoch boundaries from there. Any locking would just be defensive against future code changes altering that pattern, and such changes would also break the synchonization between the two methods. We could split these two values into a separate config struct, but as far as I can tell go doesn't have immutable structures, so we're still relying on "don't do that then".

From this point of view, I think [this lock](https://github.com/brave-experiments/star-randsrv/blob/06b312c/main.go#L294-L296) I added earlier is also unnecessary.

**Comment by NullHypothesis** [comment]
I took another look at the code and agree with the above. After running `go test -race ./...`, I did however find an unnecessary (and potentially problematic) assignment in our unit tests, which I removed in https://github.com/brave-experiments/star-randsrv/pull/39.

**Comment by NullHypothesis** [comment]
PR https://github.com/brave-experiments/star-randsrv/pull/40 addresses the other minor issues we've found. After that, we should be done with this ticket, and therefore the security review.

**Comment by NullHypothesis** [comment]
We should be done here.
